[config]
default_to_workspace = false

# ---- BUILD ----
[tasks.webui_build]
cwd = "web_ui"
description = "Build with wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = [
    "build",
    "--target",
    "web",
    "--out-dir",
    "web/pkg",
    "--out-name",
    "package",
    "--dev",
]

[tasks.webui_build_release]
cwd = "web_ui"
description = "Build with wasm-pack in release mode"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = [
    "build",
    "--target",
    "web",
    "--out-dir",
    "web/pkg",
    "--out-name",
    "package",
]

[tasks.backend_build_release]
description = "Build backend in release mode"
command = "cargo"
args = ["build", "--release", "-p", "backend"]

# ---- Build/Run on local machine ---- #
[tasks.create_local_env]
command = "docker-compose"
args = ["-f", "deployment/docker-compose-local.yaml", "up", "-d"]

[tasks.backend_run_local]
dependencies = ["create_local_env"]
env = { "RUST_LOG" = "debug", "DATABASE_URL" = "postgres://sepa:sepa@localhost/sepa", "AUTHORITY" = "https://dev-i-l2f2pc.eu.auth0.com/", "RUST_BACKTRACE" = "full" }
description = "Run backend on server"
command = "cargo"
args = ["run", "-p", "backend"]


# ---- Build/deploy on server ---- #

[tasks.backend_docker_build_image]
description = "Build docker image localy"
command = "docker"
args = [
    "build",
    ".",
    "-f",
    "deployment/Dockerfile",
    "-t",
    "ljufa/sepama-backend:latest",
]
[tasks.re_create_containers]
description = "Re-create docker containers with `latest` images using docker-compose"
command = "docker-compose"
args = ["-f", "deployment/docker-compose-server.yaml", "up", "-d"]

[tasks.redeploy]
dependencies = [
    "backend_build_release",
    "webui_build_release",
    "backend_docker_build_image",
    "re_create_containers",
]
