oauth_client_id := env_var('MYSEPA_OAUTH_CLIENT_ID')
oauth_client_secret := env_var('MYSEPA_OAUTH_CLIENT_SECRET')

fmt:
    @cargo fmt

generate-token:
    @curl --request POST \
        --url https://dev-i-l2f2pc.eu.auth0.com/oauth/token \
        --header 'content-type: application/json' \
        --data '{"client_id":"{{oauth_client_id}}","client_secret":"{{oauth_client_secret}}","audience":"http://mysepa-backend/api","grant_type":"client_credentials"}'
